// cart action
export const LOAD_CART_ITEMS = 'LOAD_CART_ITEMS';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

// Product actions (Async)
export const FETCH_PRODUCT_INIT = 'FETCH_PRODUCT_INIT';
export const FETCH_PRODUCTS_INIT = 'FETCH_PRODUCTS_INIT';
export const SAVE_PRODUCT_INIT = 'SAVE_PRODUCT_INIT';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_FAILURE = 'SAVE_PRODUCT_FAILURE';
